<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Lab.L5</AssemblyName>
    <RootNamespace>CulinaryBlog.Practice.Lab5</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
</Project>