<Project Sdk="Microsoft.NET.Sdk">
<ItemGroup>
<ProjectReference Include="../CulinaryBlog.Application/CulinaryBlog.Application.csproj" />
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
</ItemGroup>
</Project>
